name: player
description: An absolute bare-bones web app.
# version: 1.0.0
#homepage: https://www.example.com
#author: SERAGUD <email@example.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  common:
    path: ../common
  wclient:
    path: ../wclient

dev_dependencies:
  build_runner: ^1.1.2
  build_web_compilers: ^1.0.0
  pedantic: ^1.0.0
